server:
  port: 8888
#  servlet:
#    context-path: /api
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: mockup
          uri: lb://mockup
          predicates:
            - Path=/mockup/**
          filters:
            - RemoveRequestHeader=Cookie
            - name: CircuitBreaker
              args:
                name: mockup
#            - RewritePath=/api/mockup/admin/(?<path>.*), /mockup/admin/$\{path}

#      httpclient:
#        wiretap: true
#      httpserver:
#        wiretap: true

logging:
  level:
    reactor:
      netty: DEBUG
    org:
      springframework:
        cloud:
          gateway: TRACE
